### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by ghost** [CodeForWinstonSalem/forsyth-nc-food-pantries#2]
It seems the cross domain request to the google spreadsheet is not allowed by the browser - if you open the page on GitHub pages none of the markers appear.

We will need to find an alternative way to access the data when running on the web.

**Comment by mdec** [comment]
Ah yeah, I was only testing this locally and forgot about that. I read this page (https://coderwall.com/p/duapqq/use-a-google-spreadsheet-as-your-json-backend) about getting the data as JSON using cors.io as a proxy. I updated map.html with this fix.

Seems like an okay approach for now while it's under development, since it's a big advantage to keep Google Sheets as a simple and accessible data store. Let me know you have any other ideas.
